name: permitpro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter_typeahead: ^5.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ðŸ”¥ Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.2.0
  image_picker: ^1.0.7
  supabase_flutter: ^2.5.3
  shared_preferences: ^2.5.3
  photo_view: ^0.15.0
  file_picker: ^10.3.3
  lottie: ^3.3.2
  url_launcher: ^6.3.2
  syncfusion_flutter_pdfviewer: ^31.1.20
  # firebase_messaging: ^15.0.3   # uncomment later when you add push

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/bicon.png"
  adaptive_icon_foreground: "assets/icon/ficon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/icon/bicon.png
    - assets/icon/ficon.png
